[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "node server.js"

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"