[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/wd/hub/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.envs]
SE_OPTS = "--host 0.0.0.0 --port 4444"
SE_NODE_MAX_SESSIONS = "5"
SE_NODE_SESSION_TIMEOUT = "300"
SE_START_XVFB = "true"